'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
'
Namespace BOIService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DmsDocScanWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DmsDocScanWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CheckScanStartJobOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetScanJobParaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCurrentFileListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SaveFileScanOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetJobStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteAttachFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BOIScan.My.MySettings.Default.BOIScan_BOIService_DmsDocScanWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CheckScanStartJobCompleted As CheckScanStartJobCompletedEventHandler
        
        '''<remarks/>
        Public Event GetScanJobParaCompleted As GetScanJobParaCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCurrentFileListCompleted As GetCurrentFileListCompletedEventHandler
        
        '''<remarks/>
        Public Event SaveFileScanCompleted As SaveFileScanCompletedEventHandler
        
        '''<remarks/>
        Public Event SetJobStatusCompleted As SetJobStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteAttachFileCompleted As DeleteAttachFileCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckScanStartJob", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckScanStartJob(ByVal ClientIP As String) As DocumentScanJobPara
            Dim results() As Object = Me.Invoke("CheckScanStartJob", New Object() {ClientIP})
            Return CType(results(0),DocumentScanJobPara)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckScanStartJobAsync(ByVal ClientIP As String)
            Me.CheckScanStartJobAsync(ClientIP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckScanStartJobAsync(ByVal ClientIP As String, ByVal userState As Object)
            If (Me.CheckScanStartJobOperationCompleted Is Nothing) Then
                Me.CheckScanStartJobOperationCompleted = AddressOf Me.OnCheckScanStartJobOperationCompleted
            End If
            Me.InvokeAsync("CheckScanStartJob", New Object() {ClientIP}, Me.CheckScanStartJobOperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckScanStartJobOperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckScanStartJobCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckScanStartJobCompleted(Me, New CheckScanStartJobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetScanJobPara", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetScanJobPara(ByVal vJobID As Long) As DocumentScanJobPara
            Dim results() As Object = Me.Invoke("GetScanJobPara", New Object() {vJobID})
            Return CType(results(0),DocumentScanJobPara)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetScanJobParaAsync(ByVal vJobID As Long)
            Me.GetScanJobParaAsync(vJobID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetScanJobParaAsync(ByVal vJobID As Long, ByVal userState As Object)
            If (Me.GetScanJobParaOperationCompleted Is Nothing) Then
                Me.GetScanJobParaOperationCompleted = AddressOf Me.OnGetScanJobParaOperationCompleted
            End If
            Me.InvokeAsync("GetScanJobPara", New Object() {vJobID}, Me.GetScanJobParaOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetScanJobParaOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetScanJobParaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetScanJobParaCompleted(Me, New GetScanJobParaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentFileList", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCurrentFileList(ByVal RefID As Long) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("GetCurrentFileList", New Object() {RefID})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCurrentFileListAsync(ByVal RefID As Long)
            Me.GetCurrentFileListAsync(RefID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCurrentFileListAsync(ByVal RefID As Long, ByVal userState As Object)
            If (Me.GetCurrentFileListOperationCompleted Is Nothing) Then
                Me.GetCurrentFileListOperationCompleted = AddressOf Me.OnGetCurrentFileListOperationCompleted
            End If
            Me.InvokeAsync("GetCurrentFileList", New Object() {RefID}, Me.GetCurrentFileListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCurrentFileListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCurrentFileListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCurrentFileListCompleted(Me, New GetCurrentFileListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveFileScan", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveFileScan(ByVal vJobID As Long, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal FileByte() As Byte, ByVal FileExt As String, ByVal FileDesc As String) As Boolean
            Dim results() As Object = Me.Invoke("SaveFileScan", New Object() {vJobID, FileByte, FileExt, FileDesc})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SaveFileScanAsync(ByVal vJobID As Long, ByVal FileByte() As Byte, ByVal FileExt As String, ByVal FileDesc As String)
            Me.SaveFileScanAsync(vJobID, FileByte, FileExt, FileDesc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SaveFileScanAsync(ByVal vJobID As Long, ByVal FileByte() As Byte, ByVal FileExt As String, ByVal FileDesc As String, ByVal userState As Object)
            If (Me.SaveFileScanOperationCompleted Is Nothing) Then
                Me.SaveFileScanOperationCompleted = AddressOf Me.OnSaveFileScanOperationCompleted
            End If
            Me.InvokeAsync("SaveFileScan", New Object() {vJobID, FileByte, FileExt, FileDesc}, Me.SaveFileScanOperationCompleted, userState)
        End Sub
        
        Private Sub OnSaveFileScanOperationCompleted(ByVal arg As Object)
            If (Not (Me.SaveFileScanCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SaveFileScanCompleted(Me, New SaveFileScanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetJobStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetJobStatus(ByVal vJobID As Long, ByVal JobStatusID As JobStatus) As Boolean
            Dim results() As Object = Me.Invoke("SetJobStatus", New Object() {vJobID, JobStatusID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetJobStatusAsync(ByVal vJobID As Long, ByVal JobStatusID As JobStatus)
            Me.SetJobStatusAsync(vJobID, JobStatusID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetJobStatusAsync(ByVal vJobID As Long, ByVal JobStatusID As JobStatus, ByVal userState As Object)
            If (Me.SetJobStatusOperationCompleted Is Nothing) Then
                Me.SetJobStatusOperationCompleted = AddressOf Me.OnSetJobStatusOperationCompleted
            End If
            Me.InvokeAsync("SetJobStatus", New Object() {vJobID, JobStatusID}, Me.SetJobStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetJobStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetJobStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetJobStatusCompleted(Me, New SetJobStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAttachFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteAttachFile(ByVal vID As Long) As Boolean
            Dim results() As Object = Me.Invoke("DeleteAttachFile", New Object() {vID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAttachFileAsync(ByVal vID As Long)
            Me.DeleteAttachFileAsync(vID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAttachFileAsync(ByVal vID As Long, ByVal userState As Object)
            If (Me.DeleteAttachFileOperationCompleted Is Nothing) Then
                Me.DeleteAttachFileOperationCompleted = AddressOf Me.OnDeleteAttachFileOperationCompleted
            End If
            Me.InvokeAsync("DeleteAttachFile", New Object() {vID}, Me.DeleteAttachFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteAttachFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteAttachFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteAttachFileCompleted(Me, New DeleteAttachFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DocumentScanJobPara
        
        Private idField As Long
        
        Private cREATE_BYField As String
        
        Private cREATE_ONField As Date
        
        Private uPDATE_BYField As String
        
        Private uPDATE_ONField As System.Nullable(Of Date)
        
        Private jOB_START_DATEField As Date
        
        Private cLIENT_IPField As String
        
        Private cLIENT_PAGEField As String
        
        Private cLIENT_BROWSERField As String
        
        Private cLIENT_SESSIONIDField As String
        
        Private rEF_IDField As Long
        
        Private sTART_STATUSField As Char
        
        Private cHILD_DOCUMENT_SCAN_TEMP_document_scan_job_idField As System.Data.DataTable
        
        '''<remarks/>
        Public Property ID() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CREATE_BY() As String
            Get
                Return Me.cREATE_BYField
            End Get
            Set
                Me.cREATE_BYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CREATE_ON() As Date
            Get
                Return Me.cREATE_ONField
            End Get
            Set
                Me.cREATE_ONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UPDATE_BY() As String
            Get
                Return Me.uPDATE_BYField
            End Get
            Set
                Me.uPDATE_BYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UPDATE_ON() As System.Nullable(Of Date)
            Get
                Return Me.uPDATE_ONField
            End Get
            Set
                Me.uPDATE_ONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property JOB_START_DATE() As Date
            Get
                Return Me.jOB_START_DATEField
            End Get
            Set
                Me.jOB_START_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLIENT_IP() As String
            Get
                Return Me.cLIENT_IPField
            End Get
            Set
                Me.cLIENT_IPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLIENT_PAGE() As String
            Get
                Return Me.cLIENT_PAGEField
            End Get
            Set
                Me.cLIENT_PAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLIENT_BROWSER() As String
            Get
                Return Me.cLIENT_BROWSERField
            End Get
            Set
                Me.cLIENT_BROWSERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLIENT_SESSIONID() As String
            Get
                Return Me.cLIENT_SESSIONIDField
            End Get
            Set
                Me.cLIENT_SESSIONIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property REF_ID() As Long
            Get
                Return Me.rEF_IDField
            End Get
            Set
                Me.rEF_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property START_STATUS() As Char
            Get
                Return Me.sTART_STATUSField
            End Get
            Set
                Me.sTART_STATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CHILD_DOCUMENT_SCAN_TEMP_document_scan_job_id() As System.Data.DataTable
            Get
                Return Me.cHILD_DOCUMENT_SCAN_TEMP_document_scan_job_idField
            End Get
            Set
                Me.cHILD_DOCUMENT_SCAN_TEMP_document_scan_job_idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum JobStatus
        
        '''<remarks/>
        ProgramStarted
        
        '''<remarks/>
        ProgramClosed
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub CheckScanStartJobCompletedEventHandler(ByVal sender As Object, ByVal e As CheckScanStartJobCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckScanStartJobCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocumentScanJobPara
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocumentScanJobPara)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetScanJobParaCompletedEventHandler(ByVal sender As Object, ByVal e As GetScanJobParaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetScanJobParaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocumentScanJobPara
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocumentScanJobPara)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub GetCurrentFileListCompletedEventHandler(ByVal sender As Object, ByVal e As GetCurrentFileListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCurrentFileListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub SaveFileScanCompletedEventHandler(ByVal sender As Object, ByVal e As SaveFileScanCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaveFileScanCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub SetJobStatusCompletedEventHandler(ByVal sender As Object, ByVal e As SetJobStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetJobStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub DeleteAttachFileCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteAttachFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteAttachFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
