'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5485.
'
Namespace eSSO
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ssoSoap", [Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class sso
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SignInOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SignInTokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private VerifyTokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SignOutOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LinqWS.My.MySettings.Default.LinqWS_eSSO_sso
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SignInCompleted As SignInCompletedEventHandler
        
        '''<remarks/>
        Public Event SignInTokenCompleted As SignInTokenCompletedEventHandler
        
        '''<remarks/>
        Public Event VerifyTokenCompleted As VerifyTokenCompletedEventHandler
        
        '''<remarks/>
        Public Event SignOutCompleted As SignOutCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sso.boi.co.th/SignIn", RequestNamespace:="http://sso.boi.co.th/", ResponseNamespace:="http://sso.boi.co.th/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SignIn(ByVal username As String, ByVal password As String) As TResultOfUserProfile
            Dim results() As Object = Me.Invoke("SignIn", New Object() {username, password})
            Return CType(results(0),TResultOfUserProfile)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SignInAsync(ByVal username As String, ByVal password As String)
            Me.SignInAsync(username, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignInAsync(ByVal username As String, ByVal password As String, ByVal userState As Object)
            If (Me.SignInOperationCompleted Is Nothing) Then
                Me.SignInOperationCompleted = AddressOf Me.OnSignInOperationCompleted
            End If
            Me.InvokeAsync("SignIn", New Object() {username, password}, Me.SignInOperationCompleted, userState)
        End Sub
        
        Private Sub OnSignInOperationCompleted(ByVal arg As Object)
            If (Not (Me.SignInCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignInCompleted(Me, New SignInCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sso.boi.co.th/SignInToken", RequestNamespace:="http://sso.boi.co.th/", ResponseNamespace:="http://sso.boi.co.th/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SignInToken(ByVal token As String) As TResultOfUserProfile
            Dim results() As Object = Me.Invoke("SignInToken", New Object() {token})
            Return CType(results(0),TResultOfUserProfile)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SignInTokenAsync(ByVal token As String)
            Me.SignInTokenAsync(token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignInTokenAsync(ByVal token As String, ByVal userState As Object)
            If (Me.SignInTokenOperationCompleted Is Nothing) Then
                Me.SignInTokenOperationCompleted = AddressOf Me.OnSignInTokenOperationCompleted
            End If
            Me.InvokeAsync("SignInToken", New Object() {token}, Me.SignInTokenOperationCompleted, userState)
        End Sub
        
        Private Sub OnSignInTokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.SignInTokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignInTokenCompleted(Me, New SignInTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sso.boi.co.th/VerifyToken", RequestNamespace:="http://sso.boi.co.th/", ResponseNamespace:="http://sso.boi.co.th/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerifyToken(ByVal token As String) As TResultOfApplicationToken
            Dim results() As Object = Me.Invoke("VerifyToken", New Object() {token})
            Return CType(results(0),TResultOfApplicationToken)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VerifyTokenAsync(ByVal token As String)
            Me.VerifyTokenAsync(token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VerifyTokenAsync(ByVal token As String, ByVal userState As Object)
            If (Me.VerifyTokenOperationCompleted Is Nothing) Then
                Me.VerifyTokenOperationCompleted = AddressOf Me.OnVerifyTokenOperationCompleted
            End If
            Me.InvokeAsync("VerifyToken", New Object() {token}, Me.VerifyTokenOperationCompleted, userState)
        End Sub
        
        Private Sub OnVerifyTokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.VerifyTokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VerifyTokenCompleted(Me, New VerifyTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sso.boi.co.th/SignOut", RequestNamespace:="http://sso.boi.co.th/", ResponseNamespace:="http://sso.boi.co.th/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SignOut(ByVal token As String) As TResultOfBoolean
            Dim results() As Object = Me.Invoke("SignOut", New Object() {token})
            Return CType(results(0),TResultOfBoolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SignOutAsync(ByVal token As String)
            Me.SignOutAsync(token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SignOutAsync(ByVal token As String, ByVal userState As Object)
            If (Me.SignOutOperationCompleted Is Nothing) Then
                Me.SignOutOperationCompleted = AddressOf Me.OnSignOutOperationCompleted
            End If
            Me.InvokeAsync("SignOut", New Object() {token}, Me.SignOutOperationCompleted, userState)
        End Sub
        
        Private Sub OnSignOutOperationCompleted(ByVal arg As Object)
            If (Not (Me.SignOutCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SignOutCompleted(Me, New SignOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class TResultOfUserProfile
        
        Private actionCodeField As String
        
        Private errorCodeField As String
        
        Private responseTextField As String
        
        Private dataField As UserProfile
        
        '''<remarks/>
        Public Property ActionCode() As String
            Get
                Return Me.actionCodeField
            End Get
            Set
                Me.actionCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseText() As String
            Get
                Return Me.responseTextField
            End Get
            Set
                Me.responseTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Data() As UserProfile
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class UserProfile
        
        Private useridField As String
        
        Private usernameField As String
        
        Private titleNameThField As String
        
        Private firstnameField As String
        
        Private lastnameField As String
        
        Private titleNameEnField As String
        
        Private firstnameEnField As String
        
        Private lastnameEnField As String
        
        Private emailField As String
        
        Private mobileField As String
        
        Private cardIdField As String
        
        Private tokenField As String
        
        Private userStatusIdField As Integer
        
        Private employeeStatusIdField As Integer
        
        Private seqInDeptField As System.Nullable(Of Integer)
        
        Private positionThField As String
        
        Private positionENField As String
        
        Private boiPositionThField As String
        
        Private boiPositionEnField As String
        
        Private phoneNoField As String
        
        Private phoneNoExtField As String
        
        Private departmentField As String
        
        Private birthdateField As System.Nullable(Of Date)
        
        Private applicationField() As UserApplication
        
        '''<remarks/>
        Public Property Userid() As String
            Get
                Return Me.useridField
            End Get
            Set
                Me.useridField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TitleNameTh() As String
            Get
                Return Me.titleNameThField
            End Get
            Set
                Me.titleNameThField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TitleNameEn() As String
            Get
                Return Me.titleNameEnField
            End Get
            Set
                Me.titleNameEnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstnameEn() As String
            Get
                Return Me.firstnameEnField
            End Get
            Set
                Me.firstnameEnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastnameEn() As String
            Get
                Return Me.lastnameEnField
            End Get
            Set
                Me.lastnameEnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mobile() As String
            Get
                Return Me.mobileField
            End Get
            Set
                Me.mobileField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CardId() As String
            Get
                Return Me.cardIdField
            End Get
            Set
                Me.cardIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserStatusId() As Integer
            Get
                Return Me.userStatusIdField
            End Get
            Set
                Me.userStatusIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeStatusId() As Integer
            Get
                Return Me.employeeStatusIdField
            End Get
            Set
                Me.employeeStatusIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SeqInDept() As System.Nullable(Of Integer)
            Get
                Return Me.seqInDeptField
            End Get
            Set
                Me.seqInDeptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PositionTh() As String
            Get
                Return Me.positionThField
            End Get
            Set
                Me.positionThField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PositionEN() As String
            Get
                Return Me.positionENField
            End Get
            Set
                Me.positionENField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BoiPositionTh() As String
            Get
                Return Me.boiPositionThField
            End Get
            Set
                Me.boiPositionThField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BoiPositionEn() As String
            Get
                Return Me.boiPositionEnField
            End Get
            Set
                Me.boiPositionEnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNo() As String
            Get
                Return Me.phoneNoField
            End Get
            Set
                Me.phoneNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNoExt() As String
            Get
                Return Me.phoneNoExtField
            End Get
            Set
                Me.phoneNoExtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Birthdate() As System.Nullable(Of Date)
            Get
                Return Me.birthdateField
            End Get
            Set
                Me.birthdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Application() As UserApplication()
            Get
                Return Me.applicationField
            End Get
            Set
                Me.applicationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class UserApplication
        
        Private applicationIdField As String
        
        Private applicationNameField As String
        
        '''<remarks/>
        Public Property ApplicationId() As String
            Get
                Return Me.applicationIdField
            End Get
            Set
                Me.applicationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplicationName() As String
            Get
                Return Me.applicationNameField
            End Get
            Set
                Me.applicationNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class TResultOfBoolean
        
        Private actionCodeField As String
        
        Private errorCodeField As String
        
        Private responseTextField As String
        
        Private dataField As Boolean
        
        '''<remarks/>
        Public Property ActionCode() As String
            Get
                Return Me.actionCodeField
            End Get
            Set
                Me.actionCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseText() As String
            Get
                Return Me.responseTextField
            End Get
            Set
                Me.responseTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Data() As Boolean
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class ApplicationToken
        
        Private tokenIdField As Integer
        
        Private userIdField As String
        
        Private authTokenField As String
        
        Private issuedOnField As Date
        
        Private expiresOnField As Date
        
        Private clientIpField As String
        
        '''<remarks/>
        Public Property TokenId() As Integer
            Get
                Return Me.tokenIdField
            End Get
            Set
                Me.tokenIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AuthToken() As String
            Get
                Return Me.authTokenField
            End Get
            Set
                Me.authTokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuedOn() As Date
            Get
                Return Me.issuedOnField
            End Get
            Set
                Me.issuedOnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpiresOn() As Date
            Get
                Return Me.expiresOnField
            End Get
            Set
                Me.expiresOnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientIp() As String
            Get
                Return Me.clientIpField
            End Get
            Set
                Me.clientIpField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://sso.boi.co.th/")>  _
    Partial Public Class TResultOfApplicationToken
        
        Private actionCodeField As String
        
        Private errorCodeField As String
        
        Private responseTextField As String
        
        Private dataField As ApplicationToken
        
        '''<remarks/>
        Public Property ActionCode() As String
            Get
                Return Me.actionCodeField
            End Get
            Set
                Me.actionCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseText() As String
            Get
                Return Me.responseTextField
            End Get
            Set
                Me.responseTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Data() As ApplicationToken
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SignInCompletedEventHandler(ByVal sender As Object, ByVal e As SignInCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SignInCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TResultOfUserProfile
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TResultOfUserProfile)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SignInTokenCompletedEventHandler(ByVal sender As Object, ByVal e As SignInTokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SignInTokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TResultOfUserProfile
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TResultOfUserProfile)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub VerifyTokenCompletedEventHandler(ByVal sender As Object, ByVal e As VerifyTokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerifyTokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TResultOfApplicationToken
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TResultOfApplicationToken)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SignOutCompletedEventHandler(ByVal sender As Object, ByVal e As SignOutCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SignOutCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TResultOfBoolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TResultOfBoolean)
            End Get
        End Property
    End Class
End Namespace
