'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
'
Namespace BCMLinqWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BCDBinding", [Namespace]:="urn:Agent"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnProductsInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnFactoryInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnCardsInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnCompanyInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnrightInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnprocessInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnproductInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnlocaInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnCardInfo)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(returnComInfo))>  _
    Partial Public Class BCD
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getXMLCompanyInfo_funcOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateExtendRightsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateFirstImportMachineOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getCompanyProjectInfo_funcOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.LinqWS.My.MySettings.Default.LinqWS_BCMLinqWS_BCM
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getXMLCompanyInfo_funcCompleted As getXMLCompanyInfo_funcCompletedEventHandler
        
        '''<remarks/>
        Public Event updateExtendRightsCompleted As updateExtendRightsCompletedEventHandler
        
        '''<remarks/>
        Public Event updateFirstImportMachineCompleted As updateFirstImportMachineCompletedEventHandler
        
        '''<remarks/>
        Public Event getCompanyProjectInfo_funcCompleted As getCompanyProjectInfo_funcCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Agent/getXMLCompanyInfo_func", RequestNamespace:="urn:Agent", ResponseNamespace:="urn:Agent")>  _
        Public Function getXMLCompanyInfo_func(ByVal xmllogin As String, ByVal xmlpasswd As String, ByRef transactionno As String, ByVal companycode As String, ByVal lastupdate As String, ByRef page As String, ByRef errormessage As String, ByRef totalrow As String, ByRef totalpage As String, ByRef companylist() As returnComInfo) As <System.Xml.Serialization.SoapElementAttribute("status")> String
            Dim results() As Object = Me.Invoke("getXMLCompanyInfo_func", New Object() {xmllogin, xmlpasswd, transactionno, companycode, lastupdate, page})
            transactionno = CType(results(1),String)
            page = CType(results(2),String)
            errormessage = CType(results(3),String)
            totalrow = CType(results(4),String)
            totalpage = CType(results(5),String)
            companylist = CType(results(6),returnComInfo())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getXMLCompanyInfo_funcAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal transactionno As String, ByVal companycode As String, ByVal lastupdate As String, ByVal page As String)
            Me.getXMLCompanyInfo_funcAsync(xmllogin, xmlpasswd, transactionno, companycode, lastupdate, page, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getXMLCompanyInfo_funcAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal transactionno As String, ByVal companycode As String, ByVal lastupdate As String, ByVal page As String, ByVal userState As Object)
            If (Me.getXMLCompanyInfo_funcOperationCompleted Is Nothing) Then
                Me.getXMLCompanyInfo_funcOperationCompleted = AddressOf Me.OngetXMLCompanyInfo_funcOperationCompleted
            End If
            Me.InvokeAsync("getXMLCompanyInfo_func", New Object() {xmllogin, xmlpasswd, transactionno, companycode, lastupdate, page}, Me.getXMLCompanyInfo_funcOperationCompleted, userState)
        End Sub
        
        Private Sub OngetXMLCompanyInfo_funcOperationCompleted(ByVal arg As Object)
            If (Not (Me.getXMLCompanyInfo_funcCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getXMLCompanyInfo_funcCompleted(Me, New getXMLCompanyInfo_funcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Agent/updateExtendRights", RequestNamespace:="urn:Agent", ResponseNamespace:="urn:Agent")>  _
        Public Function updateExtendRights(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal cardno As String, ByVal productkey As String, ByVal rightsend As String, ByRef errormessage As String) As <System.Xml.Serialization.SoapElementAttribute("status")> String
            Dim results() As Object = Me.Invoke("updateExtendRights", New Object() {xmllogin, xmlpasswd, cardno, productkey, rightsend})
            errormessage = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateExtendRightsAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal cardno As String, ByVal productkey As String, ByVal rightsend As String)
            Me.updateExtendRightsAsync(xmllogin, xmlpasswd, cardno, productkey, rightsend, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateExtendRightsAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal cardno As String, ByVal productkey As String, ByVal rightsend As String, ByVal userState As Object)
            If (Me.updateExtendRightsOperationCompleted Is Nothing) Then
                Me.updateExtendRightsOperationCompleted = AddressOf Me.OnupdateExtendRightsOperationCompleted
            End If
            Me.InvokeAsync("updateExtendRights", New Object() {xmllogin, xmlpasswd, cardno, productkey, rightsend}, Me.updateExtendRightsOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateExtendRightsOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateExtendRightsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateExtendRightsCompleted(Me, New updateExtendRightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Agent/updateFirstImportMachine", RequestNamespace:="urn:Agent", ResponseNamespace:="urn:Agent")>  _
        Public Function updateFirstImportMachine(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal cardno As String, ByVal firstimport As String, ByRef errormessage As String) As <System.Xml.Serialization.SoapElementAttribute("status")> String
            Dim results() As Object = Me.Invoke("updateFirstImportMachine", New Object() {xmllogin, xmlpasswd, cardno, firstimport})
            errormessage = CType(results(1),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateFirstImportMachineAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal cardno As String, ByVal firstimport As String)
            Me.updateFirstImportMachineAsync(xmllogin, xmlpasswd, cardno, firstimport, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateFirstImportMachineAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal cardno As String, ByVal firstimport As String, ByVal userState As Object)
            If (Me.updateFirstImportMachineOperationCompleted Is Nothing) Then
                Me.updateFirstImportMachineOperationCompleted = AddressOf Me.OnupdateFirstImportMachineOperationCompleted
            End If
            Me.InvokeAsync("updateFirstImportMachine", New Object() {xmllogin, xmlpasswd, cardno, firstimport}, Me.updateFirstImportMachineOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateFirstImportMachineOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateFirstImportMachineCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateFirstImportMachineCompleted(Me, New updateFirstImportMachineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Agent/getCompanyProjectInfo_func", RequestNamespace:="urn:Agent", ResponseNamespace:="urn:Agent")>  _
        Public Function getCompanyProjectInfo_func(ByVal xmllogin As String, ByVal xmlpasswd As String, ByRef transactionno As String, ByVal companycode As String, ByRef errormessage As String, ByRef totalproject As String, ByRef projectlist() As returnCompanyInfo) As <System.Xml.Serialization.SoapElementAttribute("status")> String
            Dim results() As Object = Me.Invoke("getCompanyProjectInfo_func", New Object() {xmllogin, xmlpasswd, transactionno, companycode})
            transactionno = CType(results(1),String)
            errormessage = CType(results(2),String)
            totalproject = CType(results(3),String)
            projectlist = CType(results(4),returnCompanyInfo())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getCompanyProjectInfo_funcAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal transactionno As String, ByVal companycode As String)
            Me.getCompanyProjectInfo_funcAsync(xmllogin, xmlpasswd, transactionno, companycode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getCompanyProjectInfo_funcAsync(ByVal xmllogin As String, ByVal xmlpasswd As String, ByVal transactionno As String, ByVal companycode As String, ByVal userState As Object)
            If (Me.getCompanyProjectInfo_funcOperationCompleted Is Nothing) Then
                Me.getCompanyProjectInfo_funcOperationCompleted = AddressOf Me.OngetCompanyProjectInfo_funcOperationCompleted
            End If
            Me.InvokeAsync("getCompanyProjectInfo_func", New Object() {xmllogin, xmlpasswd, transactionno, companycode}, Me.getCompanyProjectInfo_funcOperationCompleted, userState)
        End Sub
        
        Private Sub OngetCompanyProjectInfo_funcOperationCompleted(ByVal arg As Object)
            If (Not (Me.getCompanyProjectInfo_funcCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getCompanyProjectInfo_funcCompleted(Me, New getCompanyProjectInfo_funcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnComInfo
        
        Private comnamethField As String
        
        Private comnameenField As String
        
        Private comcodeField As String
        
        Private comucodeField As String
        
        Private comtypeField As String
        
        Private addressField As String
        
        Private tamnameField As String
        
        Private ampnameField As String
        
        Private provnameField As String
        
        Private zipcodeField As String
        
        Private phoneField As String
        
        Private faxField As String
        
        Private chkdescField As String
        
        Private industrialnameField As String
        
        Private plantaddressField As String
        
        Private plantphoneField As String
        
        Private plantfaxField As String
        
        Private taxidField As String
        
        Private registercodeField As String
        
        Private registerdateField As String
        
        Private registercapitalField As String
        
        Private investmentcapitalField As String
        
        Private opendateField As String
        
        Private thaishareField As String
        
        Private foreignshareField As String
        
        Private laborerField As String
        
        Private saleyearField As String
        
        Private domesticField As String
        
        Private abroadField As String
        
        Private resulttypeField As String
        
        Private resultvalueField As String
        
        Private cardcountField() As returnCardInfo
        
        '''<remarks/>
        Public Property comnameth() As String
            Get
                Return Me.comnamethField
            End Get
            Set
                Me.comnamethField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comnameen() As String
            Get
                Return Me.comnameenField
            End Get
            Set
                Me.comnameenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comcode() As String
            Get
                Return Me.comcodeField
            End Get
            Set
                Me.comcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comucode() As String
            Get
                Return Me.comucodeField
            End Get
            Set
                Me.comucodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comtype() As String
            Get
                Return Me.comtypeField
            End Get
            Set
                Me.comtypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tamname() As String
            Get
                Return Me.tamnameField
            End Get
            Set
                Me.tamnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ampname() As String
            Get
                Return Me.ampnameField
            End Get
            Set
                Me.ampnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property provname() As String
            Get
                Return Me.provnameField
            End Get
            Set
                Me.provnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property zipcode() As String
            Get
                Return Me.zipcodeField
            End Get
            Set
                Me.zipcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property phone() As String
            Get
                Return Me.phoneField
            End Get
            Set
                Me.phoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property chkdesc() As String
            Get
                Return Me.chkdescField
            End Get
            Set
                Me.chkdescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property industrialname() As String
            Get
                Return Me.industrialnameField
            End Get
            Set
                Me.industrialnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property plantaddress() As String
            Get
                Return Me.plantaddressField
            End Get
            Set
                Me.plantaddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property plantphone() As String
            Get
                Return Me.plantphoneField
            End Get
            Set
                Me.plantphoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property plantfax() As String
            Get
                Return Me.plantfaxField
            End Get
            Set
                Me.plantfaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxid() As String
            Get
                Return Me.taxidField
            End Get
            Set
                Me.taxidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property registercode() As String
            Get
                Return Me.registercodeField
            End Get
            Set
                Me.registercodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property registerdate() As String
            Get
                Return Me.registerdateField
            End Get
            Set
                Me.registerdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property registercapital() As String
            Get
                Return Me.registercapitalField
            End Get
            Set
                Me.registercapitalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property investmentcapital() As String
            Get
                Return Me.investmentcapitalField
            End Get
            Set
                Me.investmentcapitalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property opendate() As String
            Get
                Return Me.opendateField
            End Get
            Set
                Me.opendateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property thaishare() As String
            Get
                Return Me.thaishareField
            End Get
            Set
                Me.thaishareField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property foreignshare() As String
            Get
                Return Me.foreignshareField
            End Get
            Set
                Me.foreignshareField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property laborer() As String
            Get
                Return Me.laborerField
            End Get
            Set
                Me.laborerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property saleyear() As String
            Get
                Return Me.saleyearField
            End Get
            Set
                Me.saleyearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property domestic() As String
            Get
                Return Me.domesticField
            End Get
            Set
                Me.domesticField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property abroad() As String
            Get
                Return Me.abroadField
            End Get
            Set
                Me.abroadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resulttype() As String
            Get
                Return Me.resulttypeField
            End Get
            Set
                Me.resulttypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resultvalue() As String
            Get
                Return Me.resultvalueField
            End Get
            Set
                Me.resultvalueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardcount() As returnCardInfo()
            Get
                Return Me.cardcountField
            End Get
            Set
                Me.cardcountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnCardInfo
        
        Private cardnoField As String
        
        Private cardcodeField As String
        
        Private cardtypeField As String
        
        Private receivedateField As String
        
        Private notificationdateField As String
        
        Private acceptdateField As String
        
        Private approvedateField As String
        
        Private certificatedateField As String
        
        Private operationduedateField As String
        
        Private operationissuedateField As String
        
        Private endprojectdateField As String
        
        Private endstatusdescField As String
        
        Private endnoField As String
        
        Private cardsectionField As String
        
        Private businesstypeField As String
        
        Private producttypeField As String
        
        Private cardstatusField As String
        
        Private locationcountField() As returnlocaInfo
        
        Private productcountField() As returnproductInfo
        
        Private processcountField() As returnprocessInfo
        
        Private rightcountField() As returnrightInfo
        
        '''<remarks/>
        Public Property cardno() As String
            Get
                Return Me.cardnoField
            End Get
            Set
                Me.cardnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardcode() As String
            Get
                Return Me.cardcodeField
            End Get
            Set
                Me.cardcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardtype() As String
            Get
                Return Me.cardtypeField
            End Get
            Set
                Me.cardtypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property receivedate() As String
            Get
                Return Me.receivedateField
            End Get
            Set
                Me.receivedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property notificationdate() As String
            Get
                Return Me.notificationdateField
            End Get
            Set
                Me.notificationdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property acceptdate() As String
            Get
                Return Me.acceptdateField
            End Get
            Set
                Me.acceptdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property approvedate() As String
            Get
                Return Me.approvedateField
            End Get
            Set
                Me.approvedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property certificatedate() As String
            Get
                Return Me.certificatedateField
            End Get
            Set
                Me.certificatedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property operationduedate() As String
            Get
                Return Me.operationduedateField
            End Get
            Set
                Me.operationduedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property operationissuedate() As String
            Get
                Return Me.operationissuedateField
            End Get
            Set
                Me.operationissuedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property endprojectdate() As String
            Get
                Return Me.endprojectdateField
            End Get
            Set
                Me.endprojectdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property endstatusdesc() As String
            Get
                Return Me.endstatusdescField
            End Get
            Set
                Me.endstatusdescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property endno() As String
            Get
                Return Me.endnoField
            End Get
            Set
                Me.endnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardsection() As String
            Get
                Return Me.cardsectionField
            End Get
            Set
                Me.cardsectionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property businesstype() As String
            Get
                Return Me.businesstypeField
            End Get
            Set
                Me.businesstypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property producttype() As String
            Get
                Return Me.producttypeField
            End Get
            Set
                Me.producttypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardstatus() As String
            Get
                Return Me.cardstatusField
            End Get
            Set
                Me.cardstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locationcount() As returnlocaInfo()
            Get
                Return Me.locationcountField
            End Get
            Set
                Me.locationcountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property productcount() As returnproductInfo()
            Get
                Return Me.productcountField
            End Get
            Set
                Me.productcountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property processcount() As returnprocessInfo()
            Get
                Return Me.processcountField
            End Get
            Set
                Me.processcountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rightcount() As returnrightInfo()
            Get
                Return Me.rightcountField
            End Get
            Set
                Me.rightcountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnlocaInfo
        
        Private locationnameField As String
        
        Private locationaddressField As String
        
        '''<remarks/>
        Public Property locationname() As String
            Get
                Return Me.locationnameField
            End Get
            Set
                Me.locationnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locationaddress() As String
            Get
                Return Me.locationaddressField
            End Get
            Set
                Me.locationaddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnProductsInfo
        
        Private productnameField As String
        
        Private maxcapacity1Field As String
        
        Private actualcapacity1Field As String
        
        Private unitname1Field As String
        
        Private maxcapacity2Field As String
        
        Private actualcapacity2Field As String
        
        Private unitname2Field As String
        
        Private workinghourField As String
        
        Private workingdayField As String
        
        Private producttypeField As String
        
        Private hscField As String
        
        Private actnameField As String
        
        '''<remarks/>
        Public Property productname() As String
            Get
                Return Me.productnameField
            End Get
            Set
                Me.productnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property maxcapacity1() As String
            Get
                Return Me.maxcapacity1Field
            End Get
            Set
                Me.maxcapacity1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actualcapacity1() As String
            Get
                Return Me.actualcapacity1Field
            End Get
            Set
                Me.actualcapacity1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property unitname1() As String
            Get
                Return Me.unitname1Field
            End Get
            Set
                Me.unitname1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property maxcapacity2() As String
            Get
                Return Me.maxcapacity2Field
            End Get
            Set
                Me.maxcapacity2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actualcapacity2() As String
            Get
                Return Me.actualcapacity2Field
            End Get
            Set
                Me.actualcapacity2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property unitname2() As String
            Get
                Return Me.unitname2Field
            End Get
            Set
                Me.unitname2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property workinghour() As String
            Get
                Return Me.workinghourField
            End Get
            Set
                Me.workinghourField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property workingday() As String
            Get
                Return Me.workingdayField
            End Get
            Set
                Me.workingdayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property producttype() As String
            Get
                Return Me.producttypeField
            End Get
            Set
                Me.producttypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property hsc() As String
            Get
                Return Me.hscField
            End Get
            Set
                Me.hscField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actname() As String
            Get
                Return Me.actnameField
            End Get
            Set
                Me.actnameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnFactoryInfo
        
        Private factoryaddressField As String
        
        Private factorydistrictField As String
        
        Private factoryamphurField As String
        
        Private factoryprovinceField As String
        
        Private factoryzipcodeField As String
        
        Private factoryindustrialField As String
        
        '''<remarks/>
        Public Property factoryaddress() As String
            Get
                Return Me.factoryaddressField
            End Get
            Set
                Me.factoryaddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property factorydistrict() As String
            Get
                Return Me.factorydistrictField
            End Get
            Set
                Me.factorydistrictField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property factoryamphur() As String
            Get
                Return Me.factoryamphurField
            End Get
            Set
                Me.factoryamphurField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property factoryprovince() As String
            Get
                Return Me.factoryprovinceField
            End Get
            Set
                Me.factoryprovinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property factoryzipcode() As String
            Get
                Return Me.factoryzipcodeField
            End Get
            Set
                Me.factoryzipcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property factoryindustrial() As String
            Get
                Return Me.factoryindustrialField
            End Get
            Set
                Me.factoryindustrialField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnCardsInfo
        
        Private cardnoField As String
        
        Private certificatedateField As String
        
        Private operationduedateField As String
        
        Private cardsectionField As String
        
        Private businesstypeField As String
        
        Private cardstatusField As String
        
        Private locationcountField() As returnFactoryInfo
        
        Private productcountField() As returnProductsInfo
        
        '''<remarks/>
        Public Property cardno() As String
            Get
                Return Me.cardnoField
            End Get
            Set
                Me.cardnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property certificatedate() As String
            Get
                Return Me.certificatedateField
            End Get
            Set
                Me.certificatedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property operationduedate() As String
            Get
                Return Me.operationduedateField
            End Get
            Set
                Me.operationduedateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardsection() As String
            Get
                Return Me.cardsectionField
            End Get
            Set
                Me.cardsectionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property businesstype() As String
            Get
                Return Me.businesstypeField
            End Get
            Set
                Me.businesstypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardstatus() As String
            Get
                Return Me.cardstatusField
            End Get
            Set
                Me.cardstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locationcount() As returnFactoryInfo()
            Get
                Return Me.locationcountField
            End Get
            Set
                Me.locationcountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property productcount() As returnProductsInfo()
            Get
                Return Me.productcountField
            End Get
            Set
                Me.productcountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnCompanyInfo
        
        Private comcodeField As String
        
        Private comnamethField As String
        
        Private comnameenField As String
        
        Private comtypeField As String
        
        Private addressField As String
        
        Private districtField As String
        
        Private amphurField As String
        
        Private provinceField As String
        
        Private zipcodeField As String
        
        Private phoneField As String
        
        Private faxField As String
        
        Private industrialField As String
        
        Private cardcountField() As returnCardsInfo
        
        '''<remarks/>
        Public Property comcode() As String
            Get
                Return Me.comcodeField
            End Get
            Set
                Me.comcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comnameth() As String
            Get
                Return Me.comnamethField
            End Get
            Set
                Me.comnamethField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comnameen() As String
            Get
                Return Me.comnameenField
            End Get
            Set
                Me.comnameenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property comtype() As String
            Get
                Return Me.comtypeField
            End Get
            Set
                Me.comtypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property district() As String
            Get
                Return Me.districtField
            End Get
            Set
                Me.districtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property amphur() As String
            Get
                Return Me.amphurField
            End Get
            Set
                Me.amphurField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property province() As String
            Get
                Return Me.provinceField
            End Get
            Set
                Me.provinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property zipcode() As String
            Get
                Return Me.zipcodeField
            End Get
            Set
                Me.zipcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property phone() As String
            Get
                Return Me.phoneField
            End Get
            Set
                Me.phoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property industrial() As String
            Get
                Return Me.industrialField
            End Get
            Set
                Me.industrialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cardcount() As returnCardsInfo()
            Get
                Return Me.cardcountField
            End Get
            Set
                Me.cardcountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnrightInfo
        
        Private rightdescField As String
        
        Private productdescField As String
        
        Private strdateField As String
        
        Private enddateField As String
        
        Private rightsyearField As String
        
        Private reducetaxField As String
        
        Private limittaxField As String
        
        Private machinetypeField As String
        
        Private joinmachineField As String
        
        Private machineyearField As String
        
        Private rightslocationField As String
        
        '''<remarks/>
        Public Property rightdesc() As String
            Get
                Return Me.rightdescField
            End Get
            Set
                Me.rightdescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property productdesc() As String
            Get
                Return Me.productdescField
            End Get
            Set
                Me.productdescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property strdate() As String
            Get
                Return Me.strdateField
            End Get
            Set
                Me.strdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property enddate() As String
            Get
                Return Me.enddateField
            End Get
            Set
                Me.enddateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rightsyear() As String
            Get
                Return Me.rightsyearField
            End Get
            Set
                Me.rightsyearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property reducetax() As String
            Get
                Return Me.reducetaxField
            End Get
            Set
                Me.reducetaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property limittax() As String
            Get
                Return Me.limittaxField
            End Get
            Set
                Me.limittaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property machinetype() As String
            Get
                Return Me.machinetypeField
            End Get
            Set
                Me.machinetypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property joinmachine() As String
            Get
                Return Me.joinmachineField
            End Get
            Set
                Me.joinmachineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property machineyear() As String
            Get
                Return Me.machineyearField
            End Get
            Set
                Me.machineyearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rightslocation() As String
            Get
                Return Me.rightslocationField
            End Get
            Set
                Me.rightslocationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnprocessInfo
        
        Private processnumField As String
        
        Private processdescField As String
        
        Private productdescField As String
        
        Private pathfileField As String
        
        '''<remarks/>
        Public Property processnum() As String
            Get
                Return Me.processnumField
            End Get
            Set
                Me.processnumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property processdesc() As String
            Get
                Return Me.processdescField
            End Get
            Set
                Me.processdescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property productdesc() As String
            Get
                Return Me.productdescField
            End Get
            Set
                Me.productdescField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pathfile() As String
            Get
                Return Me.pathfileField
            End Get
            Set
                Me.pathfileField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5420"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:Agent")>  _
    Partial Public Class returnproductInfo
        
        Private productnameField As String
        
        Private maxcapacity1Field As String
        
        Private actualcapacity1Field As String
        
        Private unitname1Field As String
        
        Private maxcapacity2Field As String
        
        Private actualcapacity2Field As String
        
        Private unitname2Field As String
        
        Private workinghourField As String
        
        Private workingdayField As String
        
        Private producttypeField As String
        
        Private hscField As String
        
        Private actnameField As String
        
        '''<remarks/>
        Public Property productname() As String
            Get
                Return Me.productnameField
            End Get
            Set
                Me.productnameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property maxcapacity1() As String
            Get
                Return Me.maxcapacity1Field
            End Get
            Set
                Me.maxcapacity1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actualcapacity1() As String
            Get
                Return Me.actualcapacity1Field
            End Get
            Set
                Me.actualcapacity1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property unitname1() As String
            Get
                Return Me.unitname1Field
            End Get
            Set
                Me.unitname1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property maxcapacity2() As String
            Get
                Return Me.maxcapacity2Field
            End Get
            Set
                Me.maxcapacity2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actualcapacity2() As String
            Get
                Return Me.actualcapacity2Field
            End Get
            Set
                Me.actualcapacity2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property unitname2() As String
            Get
                Return Me.unitname2Field
            End Get
            Set
                Me.unitname2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property workinghour() As String
            Get
                Return Me.workinghourField
            End Get
            Set
                Me.workinghourField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property workingday() As String
            Get
                Return Me.workingdayField
            End Get
            Set
                Me.workingdayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property producttype() As String
            Get
                Return Me.producttypeField
            End Get
            Set
                Me.producttypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property hsc() As String
            Get
                Return Me.hscField
            End Get
            Set
                Me.hscField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actname() As String
            Get
                Return Me.actnameField
            End Get
            Set
                Me.actnameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub getXMLCompanyInfo_funcCompletedEventHandler(ByVal sender As Object, ByVal e As getXMLCompanyInfo_funcCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getXMLCompanyInfo_funcCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property transactionno() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property page() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property errormessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property totalrow() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property totalpage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property companylist() As returnComInfo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(6),returnComInfo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub updateExtendRightsCompletedEventHandler(ByVal sender As Object, ByVal e As updateExtendRightsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateExtendRightsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property errormessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub updateFirstImportMachineCompletedEventHandler(ByVal sender As Object, ByVal e As updateFirstImportMachineCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateFirstImportMachineCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property errormessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")>  _
    Public Delegate Sub getCompanyProjectInfo_funcCompletedEventHandler(ByVal sender As Object, ByVal e As getCompanyProjectInfo_funcCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getCompanyProjectInfo_funcCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property transactionno() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property errormessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property totalproject() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property projectlist() As returnCompanyInfo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),returnCompanyInfo())
            End Get
        End Property
    End Class
End Namespace
